---
#DEPLOYMENT
apiVersion: ridemate/v1
kind: Deployment
metadata:
  name: ridemate
  namespace: our-namespace
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: ridemate
  template:
    metadata:
      labels:
        app: ridemate
    sepcs:
      containers:
        - name: auth_backend
          image: auth_backend:tag #change tag
          ports: 
            - containerPort: 5000
        - name: auth_frontend
          image: auth_frontend:tag #change tag
          ports: 
            - containerPort: 3000
        - name: chat_api
          image: chat_api:tag #change tag
          ports: 
            - containerPort: 5010
        - name: chat_api
          image: chat_api:tag #change tag
          ports: 
            - containerPort: 5010
        - name: composer
          image: composer:tag #change tag
          ports: 
            - containerPort: #composer port
        - name: payments
          image: payments:tag #change tag
          ports: 
            - containerPort: 8000
        - name: reviews
          image: reviews:tag #change tag
          ports: 
            - containerPort: 5005
        - name: trip
          image: trip:tag #change tag
          ports: 
            - containerPort: 5015
---
#SERVICES
apiVersion: v1
kind: Service
metadata:
  name: auth_backend-service
spec:
  selector:
    app: ridemate
    container: auth_backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: auth_frontend-service
spec:
  selector:
    app: ridemate
    container: auth_frontend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat_api-service
spec:
  selector:
    app: ridemate
    container: chat_api
  ports:
    - port: 5010
      targetPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: composer-service
spec:
  selector:
    app: ridemate
    container: composer
  ports:
    - port: #composer port
      targetPort: #composer port
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: ridemate
    container: payments
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app: ridemate
    container: reviews
  ports:
    - port: 5005
      targetPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: ridemate
    container: trip
  ports:
    - port: 5015
      targetPort: 5015
---
#INGRESS LOAD BALANCER
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-k3s
  namespace: our-namespace
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: ridemate-our-namespace.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ridemate
            port: #composer port
