---
#DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridemate
  namespace: egs-ridemate
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: ridemate
  template:
    metadata:
      labels:
        app: ridemate
    spec:
      containers:
        - name: auth-backend
          image: registry.deti:5000/egs-ridemate/auth_backend:v1 
          ports: 
            - containerPort: 5000
        - name: auth-frontend
          image: registry.deti:5000/egs-ridemate/auth_frontend:v1 
          ports: 
            - containerPort: 3000
        - name: chat-api
          image: registry.deti:5000/egs-ridemate/chat_api:v1 
          ports: 
            - containerPort: 5010
        - name: composer
          image: registry.deti:5000/egs-ridemate/composer:v1 
          ports: 
            - containerPort: 8080
        - name: payments
          image: registry.deti:5000/egs-ridemate/payments:v1 
          ports: 
            - containerPort: 8000
        - name: reviews
          image: registry.deti:5000/egs-ridemate/reviews:v1 
          ports: 
            - containerPort: 5005
        - name: trip
          image: registry.deti:5000/egs-ridemate/trip:v1 
          ports: 
            - containerPort: 5015
---
#SERVICES
apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: auth-backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-frontend-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: auth-frontend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: chat-api
  ports:
    - port: 5010
      targetPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: composer-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: composer
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: payments
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: reviews
  ports:
    - port: 5005
      targetPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: egs-ridemate
spec:
  selector:
    app: ridemate
    name: trip
  ports:
    - port: 5015
      targetPort: 5015
---
#INGRESS LOAD BALANCER
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-k3s
  namespace: egs-ridemate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: ridemate.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: composer-service
            port: 
              number: 8080
