# Generated by Django 4.1.7 on 2023-03-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user_id',
            new_name='id',
        ),
    ]
