# Generated by Django 4.1.7 on 2023-03-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_rename_user_id_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='owner_id',
            field=models.UUIDField(),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
